import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "FODApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="bg-white text-slate-50">
          <h1 className="text-center text-4xl mt-10 font-semibold text-slate-400">Crea una matriz <span className="text-slate-500">FODA</span> con IA</h1>
          <div className="fixed sm:relative max-w-4xl w-full flex h-[-webkit-fill-available] sm:h-auto sm:flex-col flex-col-reverse items-center justify-start gap-5 pt-5 sm:px-2 px-0 mx-auto">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
