import type { Metadata } from "next";
import "./globals.css";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { Title } from "@/components/Title";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages()
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages} >
          <main className="bg-white text-slate-50">
            <Title />
            <div className="fixed sm:relative max-w-4xl w-full flex h-[-webkit-fill-available] sm:h-auto sm:flex-col flex-col-reverse items-center justify-start gap-5 pt-5 sm:px-2 px-0 mx-auto">
              {children}
            </div>
          </main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
